### ISSUE TITLE
[Bug]: no devices showing up in hoobs. username and password correct

### ISSUE THREAD

**Issue by courtnage** [samemory/homebridge-eufy-security#286]
### What happened?

Thanks so much for making this plugin, I'm having some issues though, and I hope you can help. After installing hoobs and eufy plugin, no devices in my home are showing up in hoobs accessories.

### Device Type

other (UnSupported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v12 (Supported)

### Operating System

Other

11/26/2021, 10:42:51 PMEufy Security Bridge 2 starting
11/26/2021, 10:42:56 PMEufy Security Bridge 2Loaded plugin 'homebridge-eufy-security'
11/26/2021, 10:42:56 PMEufy Security Bridge 2Loading 1 platforms...
11/26/2021, 10:42:56 PMEufy Security Bridge 2EufySecurityFinished initializing Eufy Security Platform
11/26/2021, 10:42:57 PMEufy Security Bridge 2Bridge is running on port 54826.
11/26/2021, 10:42:58 PMEufy Security Bridge 2EufySecurityERRORNot connected can't continue!

config:
{
    "accessories": [],
    "platforms": [
        {
            "platform": "EufySecurity",
            "username": "xxxxx@xxxx.com",
            "password": "xxxxxxx",
            "enableCamera": true
        }
    ]
}

**Comment by breather74** [comment]
I am also having this issue.. Has anyone had any luck with fixing this?

**Comment by cankerman** [comment]
Anyone have an answer or solution for this. Same issues here as well

**Comment by schliemann** [comment]
@cankerman What version are you using? 1.0.6 should get devices. However stream is broken on 1.0.6. Will be fixed later.

**Comment by cankerman** [comment]
> @cankerman What version are you using? 1.0.6 should get devices. However stream is broken on 1.0.6. Will be fixed later.

To the best of my knowledge i am running the latest update as i just recently (last week or so) started dabbling into homebridge (hoobs). I will check when i get home to verify
i got the accessories to show 1x and even added my doorbell cam and the lock to homekit but needed to adjust permissions in the Eufy app to show a Eufy lock wifi hub(supported based on the supported devices list)   im trying to control also. 
I adjusted permissions, unistalled and then reinstalled the plugin and bridge and since that 1x no accessories shows up. I removed the bridge and accessories in the home app as well. Have tried numerous unistalls/reinstalls even factory reset hoobs to insure nothing was left behind from my previous attempts but at this point i no longer see devices/accessories being shown. Not sure if it matters since there is a hoobs windows app but i am running hoobs off a windowd pc thru the hoobs windows program. 

Thanks for your prompt reply any further assistance would be greatly appreciated

**Comment by deon-wentzel** [comment]
So I have the latest version of Hoobs and I installed the homebridge-eufy security plugin. When I first installed the plugin I had an issue with 2FA. On disabling 2FA this issue was resolved and I was able to see the Video Camera in Home APP. The other issue I had was the live streaming. I followed these instructions https://github.com/bropat/eufy-security-client/issues/79 to resolve the streaming issue. I hope this helps? BTW I am using version 1.06 of the plugin.

**Comment by schliemann** [comment]
@cankerman  Can you follow the advice from @deon-wentzel ?

**Comment by TORQS67** [comment]
I'm having the same issue. No devices showing up. I'm using hoobs.

**Comment by schliemann** [comment]
@TORQS67 And you have disabled 2FA?

**Comment by TORQS67** [comment]
> @TORQS67 And you have disabled 2FA?

Yes, 2FA disabled, admin permission granted to the guest account. Even tried changing the password but still get this "Not connected can't continue" error message.

**Comment by TORQS67** [comment]
> I'm having the same issue. No devices showing up. I'm using hoobs.

Weird enough. Now the plugin works fine and I can see my doorbell in Homekit. Didn't do anything but left it untouched overnight.

**Comment by schliemann** [comment]
Try and check the log if it is available.

**Comment by schliemann** [comment]
@courtnage Are you still having this issue?

**Comment by lenoxys** [comment]
2FA not supported on hoobs, hoobs is using the old config model and not the new UI.

**Comment by lenoxys** [comment]
at least hoobs is not supported ATM
